# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=4)),
                ('member', models.CharField(default='', max_length=120)),
                ('party', models.CharField(default='', max_length=50)),
                ('served', models.CharField(default='', max_length=120)),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('committees', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='zipSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='bills',
            name='title',
        ),
        migrations.AddField(
            model_name='bills',
            name='billHeading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bills',
            name='billText',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='bills',
            name='billTitle',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bills',
            name='latestAction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bills',
            name='sponser',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='bills',
            name='committees',
            field=models.CharField(default='', max_length=140),
        ),
    ]
