# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170426_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='committees',
        ),
        migrations.AddField(
            model_name='profile',
            name='Natural_Resources',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Rules',
            field=models.BooleanField(default=0),
        ),
    ]
