# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170427_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Natural_Resources',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Rules',
        ),
        migrations.AddField(
            model_name='profile',
            name='committees',
            field=models.CharField(default='', max_length=200),
        ),
    ]
